name: schic-3dvi
channels:
  - anaconda
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.7
  - numpy=1.17.*
  - scanpy=1.4.*
  - pandas=0.25.*
  - anndata=0.7.*
  - scvi-tools=0.8.*
  - joblib=0.13.*
  - scikit-learn=0.21.*