name: schic-3dvi
channels:
  - anaconda
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.7
  - numpy=1.16.*
  - scanpy=1.6.*
  - pandas=1.0.*
  - anndata=0.7.*
  - scvi-tools=0.8.*
  - joblib=1.0.*
  - scikit-learn=0.24.*